name: 'Impact Story Submission 📈'
description: 'Document and track the impact of SNWG Solutions in the field'
title: '[Solution Acronym] Impact Story: Brief Description'
projects: NASA-IMPACT/139

body:
  - type: markdown
    attributes:
      value: |
        ## 📝 SNWG Impact Story Submission Form
        
        Thank you for documenting this impact story! Please fill out the information below to help us track and showcase the value of SNWG solutions.
        
        ---

  - type: input
    id: Source
    attributes:
      label: '📰 Source'
      description: 'Name of the source of the impact story'
      placeholder: '(Forbes.com, EarthData.gov, SNWG SEP interview with Dr. Peanutbutter, Lead Scientist of the US Bureau of Allergies)'
    validations:
      required: true

  - type: input
    id: PublicationDate
    attributes:
      label: '📅 Publication Date'
      description: 'Date the value story was published or interview was held'
      placeholder: '2024-05-07'
    validations:
      required: true

  - type: dropdown
    id: ValueType
    attributes:
      label: '🎯 Impact Category'
      description: 'Select all applicable categories of impact (you can choose multiple)'
      multiple: true
      options:
        - '🏢 US Private-sector use case'
        - '🏛️ US Federal or State use case'
        - '🌏 Foreign government use case'
        - '🌍 Global/Foreign private use case'
    validations:
      required: true

  - type: textarea
    id: audience
    attributes:
      label: '👥 Target Audience'
      description: 'Describe the primary audience that benefits from this impact'
      placeholder: |
        Primary: Data scientists in the aviation industry
        Secondary: Private equity investors and government regulatory bodies
        Stakeholders: Aviation safety professionals and defense operators
    validations:
      required: true

  - type: textarea
    id: StorySummary
    attributes:
      label: '📋 Impact Summary'
      description: |
        Please provide:
        1. A brief overview of the impact (1-2 sentences)
        2. Key metrics or outcomes if available
        3. Any notable stakeholder feedback
      placeholder: |
        Example: The implementation of CubeSat data monitoring resulted in a 40% improvement in GPS disruption detection across conflict zones from 2020-2023. This enhanced capability has directly benefited aviation safety and defense operations, with stakeholders reporting increased confidence in navigation systems.
      render: markdown
    validations:
      required: true

  - type: dropdown
    id: SNWGSolution
    attributes:
      label: '🔍 SNWG Project'
      description: 'Which SNWG project is this publication affiliated with/supporting?'
      options: 
        - 'SNWG Program as a whole'
        - 'SNWG Component (MO, SEP, Assessment)'
        - 'C1 - ADMG'
        - 'C1 - CSDA'
        - 'C1 - DCD'
        - 'C1 - HLS'
        - 'C2 - OPERA'
        - 'C2 - AC-GEOS'
        - 'C2 - Freeboard and Ice Thickness'
        - 'C2 - Internet of Animals'
        - 'C2 - NISAR Soil Moisture'
        - 'C2 - SatCORPS'
        - 'C2 - Water Quality Product'
        - 'C3 - Air Quality Product'
        - 'C3 - Planetary Boundary Layer'
        - 'C3 - Sea Ice'
        - 'C3 - TEMPO NRT'
        - 'C3 - HLS- Vegitation Indices'
        - 'Other (Please specify in Summary)'
    validations:
      required: true

  - type: input
    id: impactLocation
    attributes:
      label: '🌍 Impact Location'
      description: 'What is the physical location most impacted by this use case/story?'
      placeholder: 'Global/Regions of Geopolitical Conflict, Montana, Uzbekistan, locations that house many cows, etc'
    validations:
      required: true

  - type: input
    id: hyperlink
    attributes:
      label: '🔗 Source Link'
      description: 'Link to the published source (if applicable)'
      placeholder: 'https://example.com/article'
    validations:
      required: false

  - type: textarea
    id: quote
    attributes:
      label: '💬 Key Quotes'
      description: 'Include relevant quotes that highlight the impact of the SNWG Solution'
      placeholder: |
        "The implementation of [Solution Name] has revolutionized our ability to track and respond to environmental changes in real-time..." - Dr. Jane Smith, Lead Researcher
      render: markdown
    validations:
      required: false

  - type: textarea
    id: metrics
    attributes:
      label: '📊 Impact Metrics'
      description: |
        Please provide any quantifiable metrics related to this impact story:
        - Number of users/organizations affected
        - Percentage improvements
        - Cost savings
        - Time savings
        - Other measurable outcomes
      placeholder: |
        - Served 150+ aviation professionals
        - Reduced detection time by 40%
        - Saved approximately $500,000 in operational costs
      render: markdown
    validations:
      required: false

  - type: textarea
    id: dependencies
    attributes:
      label: '🔄 Related Issues'
      description: |
        Add cards on which this issue depends.
        Start typing # to see a list of related issues.
      placeholder: 'Depends on #123, Related to #456'
      render: markdown
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ⚠️ Please review all information before submitting. Your impact story helps demonstrate the value of SNWG solutions!
