name: 'Impact Story Submission 📈'
description: 'Document and track the impact of SNWG Solutions using our signature narrative structure'
title: '[Solution Acronym] Impact Story: Brief Description'
projects: NASA-IMPACT/139

body:
  - type: markdown
    attributes:
      value: |
        ## 📝 SNWG Impact Story Submission Form
        
        Thank you for documenting this impact story! We use a narrative structure to showcase how SNWG solutions make a difference:
        - 🥺 The Sad Puppy: The underlying problem
        - 🛰️ The Solution: How SNWG addresses it
        - 🐶 The Happy Puppy: The positive outcome
        
        ---

  - type: input
    id: Source
    attributes:
      label: '📰 Source'
      description: 'Name of the source of the impact story (end user, publication, or interview)'
      placeholder: '(Forbes.com, EarthData.gov, SNWG SEP interview with Dr. Peanutbutter, Lead Scientist of the US Bureau of Allergies)'
    validations:
      required: true

  - type: textarea
    id: sadPuppy
    attributes:
      label: '🥺 The Sad Puppy - Problem Statement'
      description: 'Describe the underlying problem that needed to be addressed'
      placeholder: |
        What was the costly, time-consuming, or challenging situation before the SNWG solution?
        Example: "Agency scientists spent 40+ hours per week manually collecting rangeland data, limiting their ability to make timely management decisions."
      render: markdown
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: '🛰️ The Solution'
      description: 'Explain how the SNWG solution addresses the problem'
      placeholder: |
        What specific capabilities of the solution helped solve the problem?
        Include details like:
        - Technical characteristics (temporal/spectral resolution)
        - Key features that enabled better decision-making
        - Implementation approach
      render: markdown
    validations:
      required: true

  - type: textarea
    id: happyPuppy
    attributes:
      label: '🐶 The Happy Puppy - Outcome'
      description: 'Describe how the solution improved the situation'
      placeholder: |
        Provide specific improvements and quantifiable metrics where possible:
        - Time/cost savings
        - Process improvements
        - Decision-making enhancements
        - Environmental or societal benefits
      render: markdown
    validations:
      required: true

  - type: dropdown
    id: ValueType
    attributes:
      label: '🎯 Impact Category'
      description: 'Select all applicable categories of impact (you can choose multiple)'
      multiple: true
      options:
        - '🏢 US Private-sector use case'
        - '🏛️ US Federal or State use case'
        - '🌏 Foreign government use case'
        - '🌍 Global/Foreign private use case'
    validations:
      required: true

  - type: textarea
    id: audience
    attributes:
      label: '👥 Target Audience'
      description: 'Who benefits from this solution?'
      placeholder: |
        Primary Users: Who directly uses the solution?
        Stakeholders: Who benefits from the improved decision-making?
        Broader Impact: Any additional beneficiaries?
    validations:
      required: true

  - type: dropdown
    id: SNWGSolution
    attributes:
      label: '🔍 SNWG Project'
      description: 'Which SNWG project is this publication affiliated with/supporting?'
      options: 
        - 'SNWG Program as a whole'
        - 'SNWG Component (MO, SEP, Assessment)'
        - 'C1 - ADMG'
        - 'C1 - CSDA'
        - 'C1 - DCD'
        - 'C1 - HLS'
        - 'C2 - OPERA'
        - 'C2 - AC-GEOS'
        - 'C2 - Freeboard and Ice Thickness'
        - 'C2 - Internet of Animals'
        - 'C2 - NISAR Soil Moisture'
        - 'C2 - SatCORPS'
        - 'C2 - Water Quality Product'
        - 'C3 - Air Quality Product'
        - 'C3 - Planetary Boundary Layer'
        - 'C3 - Sea Ice'
        - 'C3 - TEMPO NRT'
        - 'C3 - HLS- Vegitation Indices'
        - 'Other (Please specify in Summary)'
    validations:
      required: true

  - type: input
    id: impactLocation
    attributes:
      label: '🌍 Impact Location'
      description: 'What is the physical location most impacted by this use case/story?'
      placeholder: 'Global/Regions of Geopolitical Conflict, Montana, Uzbekistan, locations that house many cows, etc'
    validations:
      required: true

  - type: textarea
    id: visualEvidence
    attributes:
      label: '🖼️ Visual Evidence'
      description: |
        Please describe any figures or images that illustrate:
        1. The underlying problem
        2. The solution in action
        3. The improved outcome
        
        Note: Actual files can be attached in the comment section after creating the issue
      placeholder: |
        Figure 1: Satellite imagery showing affected region
        Figure 2: Screenshot of the solution interface
        Figure 3: Before/after comparison demonstrating improvement
      render: markdown
    validations:
      required: false

  - type: textarea
    id: quote
    attributes:
      label: '💬 End User Quotes'
      description: 'Share powerful testimonials from solution users or stakeholders'
      placeholder: |
        "The SNWG solution has transformed our ability to respond to environmental changes. What used to take weeks now takes hours." - Dr. Jane Smith, Lead Researcher
      render: markdown
    validations:
      required: false

  - type: input
    id: PublicationDate
    attributes:
      label: '📅 Story Date'
      description: 'When did this impact occur or when was it documented?'
      placeholder: '2024-05-07'
    validations:
      required: true

  - type: input
    id: hyperlink
    attributes:
      label: '🔗 Related Links'
      description: 'Links to publications, news stories, or other documentation'
      placeholder: 'https://example.com/article'
    validations:
      required: false

  - type: textarea
    id: dependencies
    attributes:
      label: '🔄 Related Issues'
      description: |
        Add cards on which this issue depends.
        Start typing # to see a list of related issues.
      placeholder: 'Depends on #123, Related to #456'
      render: markdown
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ✨ Your impact story helps demonstrate the value of SNWG solutions in making real-world improvements!
        
        Remember:
        - Stories should be written with public sharing in mind
        - Focus on practical decision-making improvements
        - Quantifiable metrics and human impact are particularly powerful
        - Photos showing human impact (with permission) are encouraged
