name: New SEP Issue 
description: Create an Issue to track big ideas and their progress
title: 
projects: NASA-IMPACT/116 ##replace with desired project that you would like the issues to be automatically added to. Format as project/board number
body:
  - type: markdown
    attributes:
      value: |
        This is the SNWG MO Record of Project Resource or Value Submission Form. The values you add will be converted to a properly formatted Issue for the SNWG Management Office.
  - type: input
    id: Topic
    attributes:
      label: Topic
      description: Broad topic to be broached by the SNWG SEP
      placeholder: Example - HLS training Develop Bunny Hop Workshop Create Fact Sheets 
    validations: 
      required: true
  - type: textarea
    id: UltimateGoal
    attributes:
      label: Ultimate Goal
      description: Summarize the goal of this item in 1-2 plain-language sentences.
      placeholder: Example: Communicate with stakeholders in a routine (quarterly?) avenue. 
    validations:
      required: false
  - type: textarea
    id: audience
    attributes:
      label: Audience
      description: Add two to three sentences that explain the intended audience of this issue
      placeholder: solution stakeholders, DCD team, Comms team, internal MO
    validations:
      required: false
  - type: textarea
    id: dependencies
    attributes:
      label: Related Issues or files
      description: |
        Add cards on which this issue depends
        Github automatically provides a list of possible issues if you start by typing a `#`
      placeholder: depends on
