name: Move Issue to Column

on:
  issues:
    types: [opened]

jobs:
  move-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the issue title contains "Impact Story"
        id: check_title
        run: |
          if [[ "$(jq -r .issue.title "$GITHUB_EVENT_PATH")" == *"Impact Story"* ]]; then
            echo "::set-output name=move_issue::true"
          else
            echo "::set-output name=move_issue::false"
          fi

      - name: Move issue to Completed Impact Stories column
        if: steps.check_title.outputs.move_issue == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_URL: ${{ secrets.PROJECT_URL }}
        run: |
          COLUMN_NAME="Completed Impact Stories"
          ISSUE_NUMBER=$(jq -r .issue.number "$GITHUB_EVENT_PATH")

          # Extract org name, project name, and project number from the project URL
          ORG_NAME=$(echo $PROJECT_URL | cut -d'/' -f4)
          PROJECT_NAME=$(echo $PROJECT_URL | cut -d'/' -f5)
          PROJECT_NUMBER=$(echo $PROJECT_URL | cut -d'/' -f7)

          # Fetch the project ID
          PROJECT_ID=$(gh api orgs/$ORG_NAME/projects | jq -r '.[] | select(.number == '$PROJECT_NUMBER') | .id')
          
          # Fetch the project columns to find the column ID
          COLUMN_ID=$(gh api projects/$PROJECT_ID/columns | jq -r '.[] | select(.name == "'$COLUMN_NAME'") | .id')

          # Move the issue to the column
          gh api -X POST projects/columns/$COLUMN_ID/cards -f content_id="$ISSUE_NUMBER" -f content_type="Issue"
