name: Move New Impact Story Issues to Completed Column

on:
  issues:
    types: [opened]

jobs:
  move-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the issue uses NewImpactStory.yml template
        id: check_template
        run: |
          if [[ "$(jq -r .issue.body "$GITHUB_EVENT_PATH")" == *"<!-- NewImpactStory.yml -->"* ]]; then
            echo "::set-output name=use_template::true"
          else
            echo "::set-output name=use_template::false"
          fi

      - name: Set up Node.js
        if: steps.check_template.outputs.use_template == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install GitHub CLI
        if: steps.check_template.outputs.use_template == 'true'
        run: sudo apt-get install gh -y

      - name: Authenticate GitHub CLI
        if: steps.check_template.outputs.use_template == 'true'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Move issue to Completed Impact Stories column
        if: steps.check_template.outputs.use_template == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PROJECT_URL="${{ secrets.PROJECT_URL }}"
          COLUMN_NAME="Completed Impact Stories"
          ISSUE_NUMBER=$(jq -r .issue.number "$GITHUB_EVENT_PATH")

          # Fetch the project columns to find the column ID
          PROJECT_COLUMNS_URL=$(echo "$PROJECT_URL" | sed 's/github.com/api.github.com\/repos/')
          COLUMNS_API_URL="$PROJECT_COLUMNS_URL/projects/$(basename $PROJECT_URL)/columns"
          COLUMN_ID=$(gh api "$COLUMNS_API_URL" | jq -r '.[] | select(.name == "'$COLUMN_NAME'") | .id')

          # Add the issue to the column
          gh api -X POST "$COLUMNS_API_URL/$COLUMN_ID/cards" -F "content_id=$ISSUE_NUMBER" -F "content_type=Issue"
