# This is a basic workflow to help you get started with Actions

name: Move New Impact Story Issues to Completed Impact Stories Column

on:
  issues:
    types: [opened]

jobs:
  move-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the issue uses NewImpactStory.yml template
        id: check_template
        run: |
          if [[ "$(jq -r .issue.body "$GITHUB_EVENT_PATH")" == *"<!-- NewImpactStory.yml -->"* ]]; then
            echo "::set-output name=use_template::true"
          else
            echo "::set-output name=use_template::false"
          fi

      - name: Move issue to Completed Impact Stories column
        if: steps.check_template.outputs.use_template == 'true'
        uses: actions-ecosystem/action-move-project-column@v1
        with:
          # Modify the following URL to your project's URL
          project-url: ${{ secrets.SNWGMOSEPPROJECT_URL }}
          # Modify the following column name to your target column's name
          column-name: 'Completed Impact Stories'
          # Use the GitHub token for authentication
          github-token: ${{ secrets.GITHUB_TOKEN }}
